name: build Bicep file and Update ARM template
env: 
  ARTIFACT_DIR: "./template"
  
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - run: "mkdir $ARTIFACT_DIR"
      - name: Build Arm Template From Bicep
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: "az bicep build --file ./arm-templates/main.bicep --outdir $ARTIFACT_DIR"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: "$ARTIFACT_DIR"
          

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
