name: build Bicep file and Update ARM template

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: Build Arm Template From Bicep
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: az bicep build --file ./arm-templates/main.bicep

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ./arm-templates/main.json

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
