@v4name: build Bicep file and Update ARM template
env: 
  ARTIFACT_DIR: "./template"
  
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - run: "mkdir ${{ env.ARTIFACT_DIR }}"
        name: Create Artifact Di"
      
      - name: Build Arm Template From Bicep
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: "az bicep build --file ./arm-templates/main.bicep --outdir ${{ env.ARTIFACT_DIR }}"
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-artifact
          path: ${{ env.ARTIFACT_DIR }}
          

      - name: Deploy GitHub Pages site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.ARTIFACT_DIR }}

