name: build Bicep file and Update ARM template

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Build Arm Template From Bicep
        uses: Azure/cli@v1.0.7
        with:
          # Specify the script here
          inlineScript: az bicep build --file .\arm-templates\main.bicep    
      - name: Update ARM Template json file
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.base_ref }}
